### ISSUE TITLE
Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by paulirish** [scottgonzalez/pretty-diff#20]
Here's what I get while running pretty-diff on master.

```bash
$ pretty-diff
/Users/paulirish/.homebrew/lib/node_modules/pretty-diff/diff.js:48
		files[ filename ].push( line );
		                 ^
TypeError: Cannot read property 'push' of undefined
    at /Users/paulirish/.homebrew/lib/node_modules/pretty-diff/diff.js:48:20
    at Array.forEach (native)
    at splitByFile (/Users/paulirish/.homebrew/lib/node_modules/pretty-diff/diff.js:35:21)
    at ChildProcess.<anonymous> (/Users/paulirish/.homebrew/lib/node_modules/pretty-diff/diff.js:25:14)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
```

**Comment by paulirish** [comment]
Ah, it's because of two issues

1. `color.ui = always` will toss in color codes and mess up the `^diff --git` regex
1. i'm currently doing diff on a merge conflict which uses `diff --cc` instead. ([what --cc is about](https://lists.gnu.org/archive/html/emacs-devel/2010-01/msg01182.html))

raw output:

```
[1;33mdiff --cc Source/devtools/front_end/timeline/TimelinePanel.js[m
```
