### ISSUE TITLE
Temp Directory Error on Windows

### ISSUE THREAD

**Issue by kpollich** [scottgonzalez/pretty-diff#25]
`/tmp` or `C:\tmp` does not exist by default on Windows, so this error is thrown

```
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\tmp\diff.html'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1224:33)
    at generatePrettyDiff (C:\Users\kylepollich\AppData\Roaming\npm\node_modules\pretty-diff\pretty-diff.js:39:5)
    at C:\Users\kylepollich\AppData\Roaming\npm\node_modules\pretty-diff\pretty-diff.js:25:2
    at ChildProcess.<anonymous> (C:\Users\kylepollich\AppData\Roaming\npm\node_modules\pretty-diff\diff.js:30:4)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by scottgonzalez** [comment]
This should be fixed in v.0.5.0.
